from colorama import Fore, Back, Style, init, deinit

# initialize colorame
init()

# import 'color palette'
# Basic colors
COLOR_RESET = Fore.RESET
COLOR_BLACK = Fore.BLACK
COLOR_BLACK = Fore.WHITE
COLOR_RED = Fore.RED
COLOR_GREEN = Fore.GREEN
COLOR_YELLOW = Fore.YELLOW
COLOR_BLUE = Fore.BLUE
COLOR_MAGENTA = Fore.MAGENTA
COLOR_CYAN = Fore.CYAN
# Background colors
COLOR_BACK_RESET = Back.RESET
COLOR_BACK_BLACK = Back.BLACK
COLOR_BACK_WHITE = Back.WHITE
COLOR_BACK_RED = Back.RED
COLOR_BACK_GREEN = Back.GREEN
COLOR_BACK_YELLOW = Back.YELLOW
COLOR_BACK_BLUE = Back.BLUE
COLOR_BACK_MAGENTA = Back.MAGENTA
COLOR_BACK_CYAN = Back.CYAN
# Text styles
COLOR_STYLE_NORMAL = Style.NORMAL
COLOR_STYLE_DIM = Style.DIM
COLOR_STYLE_BRIGHT = Style.BRIGHT

COLOR_RESET_ALL = Style.RESET_ALL

# deinitialize colorama
deinit()
