blank_issues_enabled: false
contact_links:
  - name: GitHub Bane Of Wargs Discussion
    url: https://github.com/Dungeons-of-Kathallion/Bane-Of-Wargs/discussions
    about: Please ask and answer questions here.
  - name: My email address
    url: angelo.longo13@outlook.com
    about: If you want to talk privately.
