name: Copyright Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types: [opened, synchronize]

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:

  validate_copyright:
    name: Copyright Checks
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        show-progress: false
    - name: Install dependencies
      run: python3 -m pip install --user python-debian
    - name: Validate copyright file with python-debian
      run: python3 .github/code_checks/copyright.py
    - name: Validate copyright file with debian-control-linter
      uses: tibetiroka/debian-control-linter-action@v1
      with:
        type: 'debian/copyright'
        file: 'copyright'
        preset: 'strict'
        enable: 'trailingSpace,upstreamContactStyle,urlForceHttps,fieldNameCapitalization,maintainerNameFullStop,urlExists,copyrightSourceStyle'
