name: Python Syntax Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]
    types:
      - synchronize
      - opened

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: false

jobs:
  lint:
    name: Python Syntax Checks
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          show-progress: false
      - uses: cclauss/Find-Python-syntax-errors-action@master
