name: Update Submodules
on:
  schedule:
  # run daily at midnight
  - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Fix Checkout Problems
        run: git config --global core.protectNTFS false
      - uses: actions/checkout@v4
        with:
          show-progress: false
      # Initialize or update each one recursively
      - name: Pull & update submodules recursively
        run: |
          git fetch
          
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions - update submodules"
          git checkout submodule-updates-patches
          git submodule update --init --recursive
          git submodule update --remote --recursive

          git commit -am "Update submodules"
          git push
          
          echo "# Submodule Update\n`master`<--`submodules-updates`" >> body_content.txt
          gh pr create -a @OcelotWalrus -b master -F body_content.txt -t "Submodules Updates" -l "submodule updates" 
