name: Update Submodules
on:
  schedule:
  # run daily at midnight
  - cron: '0 * * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Initialize or update each one recursively
      - name: Pull & update submodules recursively
        run: |
          git checkout submodule-updates-patches
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions - update submodules"
          git submodule update --init --recursive
          git submodule update --remote --recursive

      # Commit to the repo under the GitHub actions user to ensure we have
      # reasonable logging to trace back
      - name: Commit & push changes
        run: |
          git commit -am "Update submodules" || echo "No changes to commit"
          git push
      # Create the PR to merge the submodules update to the master branch
      - name: Create PR
        run: |
          echo "# Submodule Update\n`master`<--`submodules-updates`" >> body_content.txt
          gh pr create -a @OcelotWalrus -b master -F body_content.txt -t "Submodules Updates" -l "submodule updates" 
